# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ctosb
description: alan3058 github
url: "http://alan3058.github.io"

author:
  name: 雪碧心拔凉
  email: 361225485@qq.com
  github: alan3058
  bio: just do it!

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

paginate: 5

BASE_PATH:

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap


# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 4a5819a9e98f0387b829                            #生成的clientID
  clientSecret: a44530afd651b7207d0fb8e5d1a81e50ae8f9021    #生成的clientSecret
  repo: alan3058.github.io    #仓库名称
  owner: alan3058    #github用户名
  admin: 雪碧心拔凉
  distractionFreeMode: true #是否启用类似FB的阴影遮罩
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
